["1.9"]
sha256 = "sha256-BTvCdW1aHcVgxb11s5g2njrLWIIi7jg4qs2XWhV66Xs="
vendorHash = "sha256-VVqu12MnRz0yAmgiYt7eqAy/YBsmak/xT0yiECDHz3c="

["1.10"]
sha256 = "sha256-fQDoxGcgiU+5o/Bf/+eKE5adkV9Pck7incjhxHvC6XQ="
vendorHash = "sha256-9Fu8dyYFPDUgtT4ciLyvfgd2t6D+UuNCgUnCQvaLJzs="

["1.11"]
sha256 = "sha256-zKIge2oEgytaX5TFjZRgPyGLq0iWfTe+xcVHRHNqMjU="
vendorHash = "sha256-AIBoXP1zpDaFzMxO8qBoydNDpvAYC4Vy/qT8UU72xW8="

["1.12"]
sha256 = "sha256-UZKBXlqRj4+kVTs0C4O8qiyOVGiuHwYmgnY6wfvPZsI="
vendorHash = "sha256-ZvotBEq585S7Et0lGdxAcoUcEBP/Ho/xC0vwOcXVFU0="

["1.13"]
sha256 = "sha256-+32f/zOrCbs01FJ8DRqY9URznuRFFnF5IZj+YLdmh00="
vendorHash = "sha256-Ddmp1OnCCEFSuIzse3JQwpdJ/K3E60z3XqQekn4M7s0="

["1.14"]
sha256 = "sha256-XHXdXw/BOac3QZl9hN9+TTkBdo88c0QD9z/w2csU9N8="
vendorHash = "sha256-FkyvH6S+sjrW07fnRGmCpYV32PwDXe/QeDV2Gg/ZZ/c="

["1.15"]
sha256 = "sha256-nX0fs5CO3DsBZd/5Tyshpld2fXEDViMzqfA7bIoxwLg="
vendorHash = "sha256-v6Pn5AEd/aPw6aPxW92Jr7tAgfZbpfYrCgsSd+UI2o4="
