{ ObjectMeta : Type
, ListMeta : Type
, ObjectReference : Type
, ResourceRequirements : Type
, ConfigMapVolumeSource : Type
, EmptyDirVolumeSource : Type
, HostPathVolumeSource : Type
, PersistentVolumeClaimVolumeSource : Type
, ProjectedVolumeSource : Type
, SecretVolumeSource : Type
, EndpointAddress : Type
, NodeAffinity : Type
, PodAffinity : Type
, PodAntiAffinity : Type
, Toleration : Type
, TopologySpreadConstraint : Type
, Probe : Type
, PersistentVolumeClaimSpec : Type
}
